version: '3'

services:
  library-app:
    image: 'library-app:latest'
    container_name: library-app
    build:
      dockerfile: Dockerfile
    depends_on:
      - library-app-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-app-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
    expose:
      - "8181"
    ports:
      - "8080:8080"

  library-app-db:
    image: 'postgres:15-alpine'
    container_name: library-app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - library-app_db:/var/lib/postgresql/data
    ports:
      - "5441:5432"

volumes:
  library-app_db:
